from django.db import models
from .user import User
from .license import License


class Repo(models.Model):
    id = models.IntegerField(primary_key=True)
    node_id = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    full_name = models.CharField(max_length=200)
    private = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="repos")
    html_url = models.URLField()
    description = models.TextField()
    fork = models.BooleanField(default=False)
    url = models.URLField()
    forks_url = models.URLField()
    keys_url = models.URLField()
    collaborators_url = models.URLField()
    teams_url = models.URLField()
    hooks_url = models.URLField()
    issue_events_url = models.URLField()
    events_url = models.URLField()
    assignees_url = models.URLField()
    branches_url = models.URLField()
    tags_url = models.URLField()
    blobs_url = models.URLField()
    git_tags_url = models.URLField()
    git_refs_url = models.URLField()
    trees_url = models.URLField()
    statuses_url = models.URLField()
    languages_url = models.URLField()
    stargazers_url = models.URLField()
    contributors_url = models.URLField()
    subscribers_url = models.URLField()
    subscription_url = models.URLField()
    commits_url = models.URLField()
    git_commits_url = models.URLField()
    comments_url = models.URLField()
    issue_comment_url = models.URLField()
    contents_url = models.URLField()
    compare_url = models.URLField()
    merges_url = models.URLField()
    archive_url = models.URLField()
    downloads_url = models.URLField()
    issues_url = models.URLField()
    pulls_url = models.URLField()
    milestones_url = models.URLField()
    notifications_url = models.URLField()
    labels_url = models.URLField()
    releases_url = models.URLField()
    deployments_url = models.URLField()
    git_url = models.CharField(max_length=200)
    ssh_url = models.CharField(max_length=200)
    clone_url = models.URLField()
    svn_url = models.URLField()
    mirror_url = models.URLField(blank=True, null=True)
    homepage = models.CharField(max_length=200, blank=True, null=True)
    size = models.IntegerField(default=0)
    stargazers_count = models.IntegerField(default=0)
    watchers_count = models.IntegerField(default=1)
    language = models.CharField(max_length=200)
    has_issues = models.BooleanField(default=False)
    has_projects = models.BooleanField(default=False)
    has_downloads = models.BooleanField(default=False)
    has_wiki = models.BooleanField(default=False)
    has_pages = models.BooleanField(default=False)
    forks_count = models.IntegerField(default=0)
    archived = models.BooleanField(default=False)
    disabled = models.BooleanField(default=False)
    open_issues_count = models.IntegerField(default=0)
    license = models.ForeignKey(License, on_delete=models.SET_NULL, null=True)
    forks = models.IntegerField(default=0)
    open_issues = models.IntegerField(default=0)
    watchers = models.IntegerField(default=1)
    default_branch = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    pushed_at = models.DateTimeField(auto_now_add=True)
