# Generated by Django 3.0.8 on 2020-07-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_auto_20200717_2122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo", name="forks_count", field=models.IntegerField(default=0),
        ),
    ]
