# Generated by Django 3.0.8 on 2020-07-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_auto_20200717_2129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo", name="open_issues", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="repo",
            name="open_issues_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="repo", name="size", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="repo",
            name="stargazers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="repo", name="watchers", field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="repo",
            name="watchers_count",
            field=models.IntegerField(default=1),
        ),
    ]
