# Generated by Django 3.0.8 on 2020-07-17 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_auto_20200717_2130"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repo",
            name="pushed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
