# Generated by Django 3.0.8 on 2020-07-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_auto_20200717_2133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="pushed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
