# Generated by Django 3.0.8 on 2020-07-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_auto_20200717_2145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="license",
            field=models.TextField(blank=True, null=True),
        ),
    ]
