# Generated by Django 3.0.8 on 2020-07-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0010_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="key",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="repo",
            name="license",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="service.License",
            ),
        ),
    ]
