# Generated by Django 3.0.8 on 2020-07-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_auto_20200717_2214"),
    ]

    operations = [
        migrations.AddField(
            model_name="nexturl",
            name="repo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="service.Repo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nexturl",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="service.User",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nexturl",
            name="entity",
            field=models.CharField(
                choices=[
                    ("REPO", "repo"),
                    ("USER", "user"),
                    ("USER_REPO", "user_repo"),
                ],
                max_length=10,
            ),
        ),
    ]
