# Generated by Django 3.0.8 on 2020-07-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0012_auto_20200717_2304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nexturl", name="url", field=models.URLField(null=True),
        ),
    ]
