# Generated by Django 3.0.8 on 2020-07-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0013_auto_20200717_2321"),
    ]

    operations = [
        migrations.RemoveField(model_name="nexturl", name="repo",),
        migrations.RemoveField(model_name="nexturl", name="user",),
        migrations.AlterField(
            model_name="nexturl",
            name="entity",
            field=models.CharField(
                choices=[("REPO", "repo"), ("USER", "user")], max_length=4
            ),
        ),
        migrations.CreateModel(
            name="UserRepoNextUrl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="service.User"
                    ),
                ),
            ],
        ),
    ]
