# Generated by Django 3.0.8 on 2020-07-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0014_auto_20200717_2330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nexturl",
            name="entity",
            field=models.CharField(
                choices=[("REPO", "repo"), ("USER", "user")], max_length=4, unique=True
            ),
        ),
    ]
