# Generated by Django 3.0.8 on 2020-07-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0015_auto_20200717_2340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
