# Generated by Django 3.0.8 on 2020-07-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0016_auto_20200718_0002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
