# Generated by Django 3.0.8 on 2020-07-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0017_auto_20200718_0016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license", name="url", field=models.URLField(null=True),
        ),
    ]
