# Generated by Django 3.0.8 on 2020-07-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0018_auto_20200718_0018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="node_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
