# Generated by Django 3.0.8 on 2020-07-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0020_auto_20200718_0159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="repo", name="node_id", field=models.CharField(max_length=200),
        ),
    ]
