# Generated by Django 3.0.8 on 2020-07-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0021_auto_20200718_0201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
