# Generated by Django 3.0.8 on 2020-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gravatar_id",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="site_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(default="User", max_length=200),
        ),
    ]
