# Generated by Django 3.0.8 on 2020-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_auto_20200717_0033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gravatar_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
