# Generated by Django 3.0.8 on 2020-07-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_auto_20200717_0033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo", name="fork", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="repo", name="private", field=models.BooleanField(default=False),
        ),
    ]
